export const tempBrands: { Id: number; Image: any }[] = [
  { Id: 1, Image: require("@/temp/categories/brands/1.png") },
  { Id: 2, Image: require("@/temp/categories/brands/2.png") },
  { Id: 3, Image: require("@/temp/categories/brands/3.png") },
  { Id: 4, Image: require("@/temp/categories/brands/4.png") },
  { Id: 5, Image: require("@/temp/categories/brands/5.png") },
  { Id: 6, Image: require("@/temp/categories/brands/6.png") },
  { Id: 7, Image: require("@/temp/categories/brands/7.png") },
  { Id: 8, Image: require("@/temp/categories/brands/8.png") },
  { Id: 9, Image: require("@/temp/categories/brands/9.png") },
  { Id: 10, Image: require("@/temp/categories/brands/10.png") },
  { Id: 11, Image: require("@/temp/categories/brands/11.png") },
  { Id: 12, Image: require("@/temp/categories/brands/12.png") },
  { Id: 13, Image: require("@/temp/categories/brands/13.png") },
  { Id: 14, Image: require("@/temp/categories/brands/14.png") },
  { Id: 15, Image: require("@/temp/categories/brands/15.png") },
  { Id: 16, Image: require("@/temp/categories/brands/10.png") },
  { Id: 17, Image: require("@/temp/categories/brands/11.png") },
  { Id: 18, Image: require("@/temp/categories/brands/12.png") },
  { Id: 19, Image: require("@/temp/categories/brands/13.png") },
  { Id: 20, Image: require("@/temp/categories/brands/14.png") },
];
