export const tempProducts = [
  {
    id: 1,
    imageSource: require("@/temp/home/products/1.webp"),
    name: "Mango Tang Jar 750g",
    price: 123,
    discountPercentage: 10,
    categoryId: "summer-special",
  },
  {
    id: 2,
    imageSource: require("@/temp/home/products/2.webp"),
    name: "Orange Tang Jar 750g",
    price: 200,
    categoryId: "summer-special",
  },
  {
    id: 3,
    imageSource: require("@/temp/home/products/3.webp"),
    name: "Rooh Afza 800 ml",
    price: 150,
    discountPercentage: 5,
    categoryId: "summer-special",
  },
  {
    id: 4,
    imageSource: require("@/temp/home/products/4.webp"),
    name: "Dry aloo bukhara irrani 250 gram- خشک آلو بخارہ",
    price: 300,
    categoryId: "summer-special",
  },
  {
    id: 5,
    imageSource: require("@/temp/home/products/5.webp"),
    name: "Special Ispaghol Chilka 10 gram - اسپغول چھلکا",
    price: 85,
    discountPercentage: 15,
    categoryId: "summer-special",
  },
  {
    id: 6,
    imageSource: require("@/temp/home/products/6.webp"),
    name: "Lays Paprika 50g",
    price: 85,
    discountPercentage: 10,
    categoryId: "snack-time-favorites",
  },
  {
    id: 7,
    imageSource: require("@/temp/home/products/7.webp"),
    name: "Maxim's Creamy Choclate Fudge Toffee Pouch 500gm - 100+ Pcs",
    price: 500,
    discountPercentage: 12,
    categoryId: "snack-time-favorites",
  },
  {
    id: 8,
    imageSource: require("@/temp/home/products/8.webp"),
    name: "Candyland NOW Chocolate",
    price: 60,
    categoryId: "snack-time-favorites",
  },
];
